version: "3"
services:
  flask-backend:
    container_name: data-plinth-flask-backend
    build: '.'
    volumes:
      - "./oidc_server.py:/srv/oidc_server.py"
      - "./MF_Hdf5.py:/srv/MF_Hdf5.py"
      - "./html-assets/static:/srv/static"
      - "./html-assets/templates:/srv/templates"
      - "./.secrets:/srv/.secrets/"
      - "./datasetImages/:/srv/datasetImages"
    ports:
      - '5000:5000'
  ngnix-reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./.secrets/data-plinth_lbl_gov.pem:/etc/nginx/ssl/server.pem"
      - "./.secrets/server.key:/etc/nginx/ssl/server.key"