version: "3"
services:
  flask-backend:
    container_name: data-plinth-flask-backend
    build: '.'
    volumes:
     #- "./server.py:/srv/server.py"
      - "./oidc_server.py:/srv/oidc_server.py"
      - "./html-assets/static:/srv/static"
      - "./html-assets/templates:/srv/templates"
      #- "./.secrets/OIDC_CLIENT_SECRETS.json:/srv/.secrets/OIDC_CLIENT_SECRETS.json"
      - "./.secrets:/srv/.secrets/"
      
    ports:
      - '5000:5000'
  ngnix-reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - ".secrets/data-plinth_lbl_gov.crt.cer:/etc/nginx/ssl/server.cer"
      - ".secrets/data-plinth.key:/etc/ngix/ssl/server.key"
